model: deepconvnet
train:
  datasets:
    bcic_iv_2a:
      arch: {
        dropout: 0.5, pool_size: 3, pool_stride: 3,
      }
      within: {
        stage1_epochs: 200, stage2_epochs: 100, batch_size: 64, lr: 0.002
      }
      cross: {
        stage1_epochs: 30, stage2_epochs: 20, batch_size: 64, lr: 0.002
      }
    bcic_iv_2b:
      arch: {
        dropout: 0.5, pool_size: 3, pool_stride: 3,
      }
      within: {
        stage1_epochs: 200, stage2_epochs: 100, batch_size: 64, lr: 0.002
      }
      cross: {
        stage1_epochs: 30, stage2_epochs: 20, batch_size: 64, lr: 0.002
      }
    bcic_iii_4a:
      arch: {
        dropout: 0.5, pool_size: 2, pool_stride: 2,
      }
      within: {
        stage1_epochs: 200, stage2_epochs: 100, batch_size: 64, lr: 0.002
      }
      cross: {
        stage1_epochs: 30, stage2_epochs: 20, batch_size: 64, lr: 0.002
      }
    wbcic_shu:
      arch: {
        dropout: 0.5, pool_size: 3, pool_stride: 3,
      }
      within: {
        stage1_epochs: 200, stage2_epochs: 100, batch_size: 64, lr: 0.002
      }
